export const ROLES = {
  ADMIN: 'Admin',
  LEADER: 'Leader',
  MEMBER: 'Member'
};

export const PERMISSIONS = {
  VIEW_MEMBERS: 'view_members',
  MANAGE_MEMBERS: 'manage_members',
  VIEW_DONATIONS: 'view_donations',
  MANAGE_DONATIONS: 'manage_donations',
  VIEW_EVENTS: 'view_events',
  MANAGE_EVENTS: 'manage_events',
  VIEW_MESSAGES: 'view_messages',
  MANAGE_MESSAGES: 'manage_messages',
  MANAGE_MINISTRIES: 'manage_ministries',
  VIEW_ANALYTICS: 'view_analytics',
  MANAGE_ANNOUNCEMENTS: 'manage_announcements',
  MANAGE_REPORTS: 'manage_reports'
};

export const rolePermissionsMap = {
  [ROLES.ADMIN]: [
    PERMISSIONS.VIEW_MEMBERS,
    PERMISSIONS.MANAGE_MEMBERS,
    PERMISSIONS.VIEW_DONATIONS,
    PERMISSIONS.MANAGE_DONATIONS,
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.MANAGE_EVENTS,
    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.MANAGE_MESSAGES,
    PERMISSIONS.MANAGE_MINISTRIES,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.MANAGE_ANNOUNCEMENTS,
    PERMISSIONS.MANAGE_REPORTS
  ],
  [ROLES.LEADER]: [
    PERMISSIONS.VIEW_MEMBERS,
    PERMISSIONS.MANAGE_MEMBERS,
    PERMISSIONS.VIEW_DONATIONS,
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.MANAGE_EVENTS,
    PERMISSIONS.VIEW_MESSAGES,
    PERMISSIONS.MANAGE_MESSAGES,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.MANAGE_ANNOUNCEMENTS
  ],
  [ROLES.MEMBER]: [
    PERMISSIONS.VIEW_MEMBERS,
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.VIEW_MESSAGES
  ]
};